<?php
register_sidebar(array(
			'name' => 'First Widget Area',
			'id' => 'first-general-wa',
			'description' => 'Before all widgets and show all pages' ,
			'before_title' => '<div class="wtitle-container"><h3 class="first-wa">',
			'after_title' => '</h3></div>',		
			'before_widget' => '<div id="%1$s" class="first-wa-container %2$s">',
			'after_widget' => '</div>',
		));
register_sidebar(array(
			'name' => 'Right Widget Area',
			'id' => 'right-general-wa',
			'description' => 'Show only rigth sidebar' ,
			'before_title' => '<div class="wtitle-container"><h3 class="first-wa">',
			'after_title' => '</h3></div>',		
			'before_widget' => '<div id="%1$s" class="first-wa-container %2$s">',
			'after_widget' => '</div>',
		));
register_sidebar(array(
			'name' => 'Left Widget Area',
			'id' => 'left-general-wa',
			'description' => 'Show only left sidebar' ,
			'before_title' => '<div class="wtitle-container"><h3 class="first-wa">',
			'after_title' => '</h3></div>',		
			'before_widget' => '<div id="%1$s" class="first-wa-container %2$s">',
			'after_widget' => '</div>',
		));
register_sidebar(array('name' => 'Last Widget Area',
			'id' => 'last-general-wa',
			'description' => 'After all widgets and show all pages' ,
			'before_title' => '<div class="wtitle-container"><h3 class="last-wa">',
			'after_title' => '</h3></div>',		
			'before_widget' => '<div id="%1$s" class="last-wa-container %2$s">',
			'after_widget' => '</div>',
		));
register_sidebar(array('name' => 'Front Page Widget Area',
			'id' => 'font-page-wa',
			'description' => 'Front Page Widget Area' ,
			'before_title' => '<div class="wtitle-container"><h3 class="front-page-wa">',
			'after_title' => '</h3></div>',		
			'before_widget' => '<div id="%1$s" class="front-page-wa-container %2$s">',
			'after_widget' => '</div>',
		));
register_sidebar(array('name' => 'Single Page Widget Area',
			'id' => 'single-wa',
			'description' => 'Single Page Widget Area' ,
			'before_title' => '<div class="wtitle-container"><h3 class="single-wa">',
			'after_title' => '</h3></div>',		
			'before_widget' => '<div id="%1$s" class="single-wa-container %2$s">',
			'after_widget' => '</div>',
		));
register_sidebar(array('name' => 'Page Widget Area',
			'id' => 'page-wa',
			'description' => 'Page Page Widget Area' ,
			'before_title' => '<div class="wtitle-container"><h3 class="page-wa">',
			'after_title' => '</h3></div>',		
			'before_widget' => '<div id="%1$s" class="page-wa-container %2$s">',
			'after_widget' => '</div>',
		));
register_sidebar(array('name' => 'Category Widget Area',
			'id' => 'category-wa',
			'description' => 'Category Widget Area' ,
			'before_title' => '<div class="wtitle-container"><h3 class="category-wa">',
			'after_title' => '</h3></div>',		
			'before_widget' => '<div id="%1$s" class="category-wa-container %2$s">',
			'after_widget' => '</div>',
		));
register_sidebar(array('name' => 'Tag Widget Area',
			'id' => 'tag-wa',
			'description' => 'Tag Widget Area' ,
			'before_title' => '<div class="wtitle-container"><h3 class="tag-wa">',
			'after_title' => '</h3></div>',		
			'before_widget' => '<div id="%1$s" class="tag-wa-container %2$s">',
			'after_widget' => '</div>',
		));
register_sidebar(array('name' => 'Author Widget Area',
			'id' => 'author-wa',
			'description' => 'Author Widget Area' ,
			'before_title' => '<div class="wtitle-container"><h3 class="author-wa">',
			'after_title' => '</h3></div>',		
			'before_widget' => '<div id="%1$s" class="author-wa-container %2$s">',
			'after_widget' => '</div>',
		));
register_sidebar(array('name' => 'Date Widget Area',
			'id' => 'author-wa',
			'description' => 'Author Widget Area' ,
			'before_title' => '<div class="wtitle-container"><h3 class="author-wa">',
			'after_title' => '</h3></div>',		
			'before_widget' => '<div id="%1$s" class="author-wa-container %2$s">',
			'after_widget' => '</div>',
		));
register_sidebar(array('name' => 'Archive Widget Area',
			'id' => 'archive-wa',
			'description' => 'Archive Widget Area' ,
			'before_title' => '<div class="wtitle-container"><h3 class="archive-wa">',
			'after_title' => '</h3></div>',		
			'before_widget' => '<div id="%1$s" class="archive-wa-container %2$s">',
			'after_widget' => '</div>',
		));
register_sidebar(array('name' => 'Search Widget Area',
			'id' => 'search-wa',
			'description' => 'Search Widget Area' ,
			'before_title' => '<div class="wtitle-container"><h3 class="search-wa">',
			'after_title' => '</h3></div>',		
			'before_widget' => '<div id="%1$s" class="search-wa-container %2$s">',
			'after_widget' => '</div>',
		));
		
/* Footer widget area */
register_sidebar(array('name' => 'Footer Widget Area 1',
			'id' => 'footer-wa1',
			'description' => 'Footer Widget Area 1' ,
			'before_title' => '<h3 class="footer-wa">',
			'after_title' => '</h3>',		
			'before_widget' => '<div id="%1$s" class="footer-wa-container %2$s">',
			'after_widget' => '</div>',
		));
register_sidebar(array('name' => 'Footer Widget Area 2',
			'id' => 'footer-wa2',
			'description' => 'Footer Widget Area 2' ,
			'before_title' => '<h3 class="footer-wa">',
			'after_title' => '</h3>',		
			'before_widget' => '<div id="%1$s" class="footer-wa-container %2$s">',
			'after_widget' => '</div>',
		));
register_sidebar(array('name' => 'Footer Widget Area 3',
			'id' => 'footer-wa3',
			'description' => 'Footer Widget Area 3' ,
			'before_title' => '<h3 class="footer-wa">',
			'after_title' => '</h3>',		
			'before_widget' => '<div id="%1$s" class="footer-wa-container %2$s">',
			'after_widget' => '</div>',
		));
register_sidebar(array('name' => 'Footer Widget Area 4',
			'id' => 'footer-wa4',
			'description' => 'Footer Widget Area 4' ,
			'before_title' => '<h3 class="footer-wa">',
			'after_title' => '</h3>',		
			'before_widget' => '<div id="%1$s" class="footer-wa-container %2$s">',
			'after_widget' => '</div>',
		));
		
/* Special widget area */
register_sidebar(array('name' => 'Page Title Widget Area',
			'id' => 'page-title-wa',
			'description' => 'Page Title Widget Area' ,
			'before_title' => '<h3 class="page-title-wa">',
			'after_title' => '</h3>',		
			'before_widget' => '<div id="%1$s" class="page-title-wa-container %2$s">',
			'after_widget' => '</div>',
		));
		
		
/* Pop up widget area */
register_sidebar(array('name' => 'Top Pop Up Left',
			'id' => 'top-popup-left-wa',
			'description' => 'Top Pop Up Left Widget Area' ,
			'before_title' => '<h3 class="top-popup-left-wa">',
			'after_title' => '</h3>',		
			'before_widget' => '<div id="%1$s" class="top-popup-left-wa-container %2$s">',
			'after_widget' => '</div>',
		));
register_sidebar(array('name' => 'Top Pop Up Right',
			'id' => 'top-popup-right-wa',
			'description' => 'Top Pop Up Right Widget Area' ,
			'before_title' => '<h3 class="top-popup-right-wa">',
			'after_title' => '</h3>',		
			'before_widget' => '<div id="%1$s" class="top-popup-right-wa-container %2$s">',
			'after_widget' => '</div>',
		));		
		
register_sidebar(array('name' => 'Bottom Pop Up Left',
			'id' => 'bottom-popup-left-wa',
			'description' => 'Bottom Pop Up Left Widget Area' ,
			'before_title' => '<h3 class="bottom-popup-left-wa">',
			'after_title' => '</h3>',		
			'before_widget' => '<div id="%1$s" class="bottom-popup-left-wa-container %2$s">',
			'after_widget' => '</div>',
		));
register_sidebar(array('name' => 'Bottom Pop Up Right',
			'id' => 'bottom-popup-right-wa',
			'description' => 'Bottom Pop Up Right Widget Area' ,
			'before_title' => '<h3 class="bottom-popup-right-wa">',
			'after_title' => '</h3>',		
			'before_widget' => '<div id="%1$s" class="bottom-popup-right-wa-container %2$s">',
			'after_widget' => '</div>',
		));
?>